### ISSUE TITLE
Spaces in names

### ISSUE THREAD

**Issue by Gjum** [okx-code/RailSwitch#1]
Signs allow spaces in destination names, the `/dest` command does not. Is there a reason for this or is it an arbitrary decision? If the latter is the case, I would advocate allowing spaces in destination names in the `/dest` command too.

**Comment by ArowShot** [comment]
Adding support doesn't change very much, the /dest command is pretty simple so just combining all of the arguments with a " " separator should do the trick. I wrote some code in #3 and after testing it, it seems to work well. Who knows if I'm missing something in my implementation, it's open for review.
